name: mi_card
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - images/
  fonts:
    - family: Mogra-Regular
      fonts:
      - asset: fonts/Mogra-Regular.ttf
    - family: Asap-SemiBold
      fonts:
      - asset: fonts/Asap-SemiBold.ttf